### PR TITLE
puppet-lint --fix

### PR DESCRIPTION
**Pull request by LadyNamedLaura**
It was breaking our pipelines. :-)

https://twitter.com/KrisBuytaert/status/847817863012528129

### CODE REVIEW

**Comment by purpleidea** [comment]
@SimonPe Cool... So I'm not really maintaining this much anymore since I'm working on https://github.com/purpleidea/mgmt/, so I'm will to ACK this assuming you're also interested in being added as a maintainer. LMK.

**Comment by Fabian1976** [comment]
I will review this today

**Comment by Fabian1976** [comment]
mmm, the code from the pr doesn't run on my side anymore.

When i run this:
```
# git checkout pr/10
# puppet apply /etc/puppetlabs/code/environments/production/manifests/ipa-server.pp
```

I get this error:
```
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: Unknown variable: '::puppet_vardirtmp'. at /etc/puppetlabs/code/environments/production/modules/ipa/manifests/vardir.pp:19:6
Warning: Unknown variable: '::puppet_vardirtmp'. at /etc/puppetlabs/code/environments/production/modules/ipa/manifests/vardir.pp:39:36
Error: Evaluation Error: Error while evaluating a Function Call, 'regsubst' parameter 'target' expects a value of type Array or String, got Undef at /etc/puppetlabs/code/environments/production/modules/ipa/manifests/vardir.pp:39:27 on node ipa.cmc.lan
```

Then, when I try to do a run on the master branch (same server, os, puppet version etc)
```
# git checkout master
# puppet apply /etc/puppetlabs/code/environments/production/manifests/ipa-server.pp 
```

It runs fine. Not perfect, I still get some warnings, but when the run finishes, I have a working IPA server.

The manifest I use is very basic:
```
node default {
  class { 'ipa::server':
    domain         => 'example.lan',
    dm_password    => 'adminpassword',
    admin_password => 'adminpassword',
    shell          => '/bin/bash'
  }
}
```

OS: CentOS Linux release 7.2.1511 (Core) 
Puppet-agent: 1.9.3-1.el7 (puppetlabs-pc1)
Puppet: 4.9.4

If it runs fine on your server, what are your settings?

**Comment by SimonPe** [comment]
@Fabian1976 damn, found the issue, probably didn't break on our side because of our older puppet (3.8)

the issue is that puppet lint "corrected" `"${::puppet_vardirtmp}" == ''` to `$::puppet_vardirtmp == ''` which of course is completely different if you try to test for the existence of the fact.

so i'm unsure what the correct way of doing this. `if defined('$::puppet_vardirtmp')` ?

**Comment by purpleidea** [comment]
On Thu, Apr 6, 2017 at 4:12 PM, Simon Peeters <notifications@github.com>
wrote:

> so i'm unsure what the correct way of doing this. if
> defined('$::puppet_vardirtmp') ?
>


I think this is not correct because defined had a weird ordering issue. But
it's been a while since I looked at this.

**Comment by Fabian1976** [comment]
I believe this would also work and would be the correct approach:
```
if $facts['puppet_vardirtmp'] == undef
  if $facts['puppet_vardir'] == undef 
```

When the above is fixed, the next error appears:
```Error: Evaluation Error: Error while evaluating a Function Call, The dm_password must be at least eight characters in length. at /etc/puppetlabs/code/environments/production/modules/ipa/manifests/server.pp:427:7 on node```

We can fix this by modifying this in server.pp:
Change this:
```
    $dm_bool = inline_template('<%= @dm_password.length < 8 ? "false":"true" %>')
    if $dm_bool != true {
```
to this:
```
    if length($dm_password) < 8 {
```

On line 426 and line 443 for admin_bool.

With both these fixes, the base run succeeds with my manifest.
I think there will still be some issues on user and/or host creation, but those might need a bigger overhaul.

If you can add these fixes, i will approve this PR.

**Comment by SimonPe** [comment]
@Fabian1976
Even though i'm a fan of the idea of `$facts`, I'm not fan of its usage.
The simple reason: It's disabled by default on puppet 3.x, so unless we drop that compat (we still use 3.8.7 in most of our stack) using `$facts` is not really an easy option.

I'm actually pro the defined solution since it does exactly what it says on the tin.
AFAIK the ordering issues @purpleidea talks about is only applicable if you use defined to check wether or not a resource is defined, not when checking a variable.

**Comment by Fabian1976** [comment]
I have tried to use defined and that also works fine on my end:
```
-  if $::puppet_vardirtmp == '' {
-    if $::puppet_vardir == '' {
+  if !defined('$::puppet_vardirtmp') {
+    if !defined('$::puppet_vardir') {
```

Zo if you could change it, I would approve.
Don't forget to also change the password length check in server.pp

**Comment by Fabian1976** [comment]
Any progress?

**Comment by bittner** [comment]
@Fabian1976 Would you merge this PR if I promised to make a new PR directly afterwards that would fix [the two lines you requested to be changed](https://github.com/purpleidea/puppet-ipa/pull/10#issuecomment-293492151)?

Maybe @SimonPe is on a sabbatical or has lost interest alltogether? It would be sad to see his contribution age unused. And really, I'd love to see a green badge on the README again.

**Comment by bittner** [comment]
I'm neither a Ruby nor a Puppet pro, so forgive my dumb question, but: The tests [only run against Puppet version 3](https://github.com/purpleidea/puppet-ipa/blob/master/.travis.yml#L20-L25). Shouldn't we also test at least Puppet 4?

**Comment by purpleidea** [comment]
@bittner The test only run against the last version I ever used when I was maintaining this. So yeah. If the other maintainers don't object, and you don't make any merge commits, I can add you as a contributor as well.

**Comment by bittner** [comment]
> I can add you as a contributor as well.

I don't think that's needed. If just someone responds to PRs in a timely manner. More importantly, we need to get the module released on PuppetForge after any changes. That would be nice.

We'd need to get this module working on Puppet 3 and 4. Can we/you merge this PR and extend the Travis configuration (in a new PR) to cover more Puppet versions?

**Comment by purpleidea** [comment]
@bittner I'm not maintaining this or writing patches for it any more, so it's up to the other maintainers. If they're unresponsive I can add new maintainers. I've moved on to mgmt, see my comment in: https://github.com/purpleidea/puppet-ipa/pull/10#issuecomment-290799171

**Comment by Fabian1976** [comment]
Ok, i've merged it. I'm using Puppet 4 and it does work on Puppet 4. I haven't used Travis before but I will have a look.

**Comment by bittner** [comment]
@Fabian1976 Thank you!

It's easy to add more Puppet versions to the Travis configuration. Just [append the target versions](https://github.com/purpleidea/puppet-ipa/blob/master/.travis.yml#L20-L25) after line 25, e.g.

``` yaml
env:
  ...
  - PUPPET_VERSION=4.0.0
  - PUPPET_VERSION=4.x.y
  - PUPPET_VERSION=4.a.b
  ...
```
I don't know Puppet well enough to be able to tell which version numbers make sense to include, sorry!
Travis will spawn a job (environment) for each of those values and run the `script` command therein. One build job for each line in the `env` section (see [the build for this PR](https://travis-ci.org/purpleidea/puppet-ipa/builds/217198554)).

The tricky part afterwards will be to make the tests all pass for the different versions.

**Pull request merged**
